general.import = ["~/.config/alacritty/themes/BloodMoon.toml"]

[env]
TERM = "xterm-256color"

[font]
normal.family = "JetBrainsMono Nerd Font"
builtin_box_drawing = true
size = 11.3

[window]
dynamic_title = true
opacity = 0.92
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

#[colors]
#draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = false
style = "Beam"

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[scrolling]
history = 100000
multiplier = 6

[terminal.shell]
program = "/usr/bin/zsh"
